- hosts: localhost
  gather_facts: no
  connection: local
  roles:
     - folders
     - folder_permissions
     - pfsense_deploy_provision
     - template_deployment

- hosts: Active_Directory
  gather_facts: no
  roles:
    - windows_server_provision_AD

- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
  gather_facts: no
  strategy: free
  tasks:
    - name: Wait For connection up
      wait_for_connection:
        timeout: 30000

- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
  roles:
    - local_users_Linux

- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
  tasks:
    - name: Misconfigured DNS
      raw: echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head ;  resolvconf --enable-updates ; resolvconf -u #sed -i -e 's/8.8.8.8/nameserver 8.8.8.8/g' /etc/resolv.conf
  become: true

- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
  become: yes
  roles:
    - disable_firewall

- hosts: DB
  become: true
  roles:
    - ansible-role-mysql-master

- hosts: DB
  become: true
  roles:
    - ansible-docker-master

#- hosts: IT_Station
#  become: yes
#  roles:
#    - powershell-ubuntu-role

- hosts: Windows1, Windows2, FTP
  gather_facts: no
  roles:
    - Windows_Client_Provision

#Individual Stuff
#- hosts: WEB
#  gather_facts: no
#  strategy: free
#  tasks:
#    - name: Wait For connection up
#      wait_for_connection:
#        timeout: 30000

#- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
#  roles:
#    - local_users_Linux

#- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
#  tasks:
#    - name: Misconfigured DNS
#      raw: echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head ;  resolvconf --enable-updates ; resolvconf -u #sed -i -e 's/8.8.8.8/nameserver 8.8.8.8/g' /etc/resolv.conf
#  become: true

#- hosts: AliExpressWindows, Ubuntu, Ubuntu2, CentOS, WEB, DB, API, WebAPI
#  become: yes
#  roles:
#    - disable_firewall