- hosts: localhost
  gather_facts: no
  connection: local
  roles:
     - folders
     - folder_permissions
     - pfsense_deploy_provision
     - template_deployment

- hosts: Active_Directory
  gather_facts: no
  roles:
    - windows_server_provision_AD

- hosts: Ubuntu1, Ubuntu2, Ubuntu3, CentOS, WEB, DB, DevServer
  gather_facts: no
  strategy: free
  tasks:
    - name: Wait For connection up
      wait_for_connection:
        timeout: 30000

- hosts: Ubuntu1, Ubuntu2, Ubuntu3, CentOS, WEB, DB, DevServer
  roles:
    - local_users_Linux

- hosts: Ubuntu1, Ubuntu2, Ubuntu3, CentOS, WEB, DB, DevServer
  tasks:
    - name: Misconfigured DNS
      raw: echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head ;  resolvconf --enable-updates ; resolvconf -u #sed -i -e 's/8.8.8.8/nameserver 8.8.8.8/g' /etc/resolv.conf
  become: true

- hosts: Ubuntu1, Ubuntu2, Ubuntu3, CentOS, WEB, DB, DevServer
  become: yes
  roles:
    - disable_firewall

- hosts: DB
  become: true
  roles:
    - ansible-role-mysql-master

- hosts: DB
  become: true
  roles:
    - ansible-docker-master

#- hosts: IT_Station
#  become: yes
#  roles:
#    - powershell-Ubuntu2-role

- hosts: Windows1, Windows2, FTP
  gather_facts: no
  roles:
    - Windows_Client_Provision
