accounts:

  - username: Admin
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: Jumpman
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: DonkeyKong
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: DonkeyKongJR
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: PacMan
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: MrsPacMan
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: Ryu
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: Ken
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: Luigi
    password: Changeme2022!
    groups:
      - Domain Admins

  - username: Qbert
    password: Changeme2022!
    groups:
      - Domain Admins
 
  - username: Sonic
    password: Changeme2022!
    groups:
      - Domain Admins
