accounts:

  - username: Admin
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Masks
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Charts
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Wannacry
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Flu
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Nimda
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Health
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Medicine
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Surgery
    password: Changeme2021!
    groups:
      - Domain Admins

  - username: Family
    password: Changeme2021!
    groups:
      - Domain Admins
 
  - username: Doctor
    password: Changeme2021!
    groups:
      - Domain Admins
